{% set name = "napari-trackpy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-trackpy-{{ version }}.tar.gz
  sha256: 33d196e8dcf486ab11961f8d84f365ad89956cfe07f8c21ad009c7c0874dca66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - setuptools-scm
    - wheel
  run:
    - magicgui
    - matplotlib-base
    - napari
    - napari-aicsimageio >=0.7.0
    - numpy
    - python >=3.8
    - qtpy
    - trackpy

test:
  imports:
    - napari_trackpy
  commands:
    - pip list 
    # - pip check # Fails due to aicsimageio dependencies
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-trackpy
  summary: Plugin to do trackpy particle tracking on microscopy data within napari
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rhoitink/napari-trackpy

extra:
  recipe-maintainers:
    - goanpeca
    - rhoitink
